import type { CreateServiceProviderDto } from '../service-providers/dto/create-service-provider.dto.js';

export const demoServiceProviders: CreateServiceProviderDto[] = [
  {
    firstName: 'Sophie',
    lastName: 'Martin',
    profession: 'Plombière',
    city: 'Paris',
    description: 'Installation et dépannage de plomberie pour les particuliers.',
    hourlyRate: 45,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Thomas',
    lastName: 'Bernard',
    profession: 'Électricien',
    city: 'Lyon',
    description: 'Diagnostic et petits travaux électriques dans votre logement.',
    hourlyRate: 50,
    imageUrl: '',
    available: false,
  },
  {
    firstName: 'Camille',
    lastName: 'Laurent',
    profession: 'Jardinière',
    city: 'Marseille',
    description: 'Entretien des jardins, taille des végétaux et aménagement des espaces verts.',
    hourlyRate: 30,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Hugo',
    lastName: 'Petit',
    profession: 'Informaticien',
    city: 'Paris',
    description: 'Assistance informatique, dépannage et accompagnement pour vos outils numériques.',
    hourlyRate: 40,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Léa',
    lastName: 'Moreau',
    profession: 'Peintre',
    city: 'Lyon',
    description: 'Préparation des surfaces et travaux de peinture pour rafraîchir vos intérieurs.',
    hourlyRate: 35,
    imageUrl: '',
    available: false,
  },
  {
    firstName: 'Adam',
    lastName: 'Roux',
    profession: 'Menuisier',
    city: 'Nantes',
    description: 'Fabrication, pose et réparation de meubles et d’aménagements en bois.',
    hourlyRate: 45,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Inès',
    lastName: 'Robert',
    profession: 'Aide ménagère',
    city: 'Marseille',
    description: 'Ménage régulier ou ponctuel et entretien soigné de votre logement.',
    hourlyRate: 25,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Lucas',
    lastName: 'Garnier',
    profession: 'Plombier',
    city: 'Nantes',
    description: 'Dépannage, réparation des fuites et installation des équipements sanitaires.',
    hourlyRate: 48,
    imageUrl: '',
    available: false,
  },
  {
    firstName: 'Emma',
    lastName: 'Faure',
    profession: 'Professeure de mathématiques',
    city: 'Lille',
    description:
      'Cours particuliers de mathématiques adaptés au niveau et aux objectifs de chaque élève.',
    hourlyRate: 30,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Nathan',
    lastName: 'André',
    profession: 'Jardinier',
    city: 'Paris',
    description: 'Entretien courant, taille et soins des plantes pour vos jardins et terrasses.',
    hourlyRate: 32,
    imageUrl: '',
    available: false,
  },
  {
    firstName: 'Sarah',
    lastName: 'Mercier',
    profession: 'Informaticienne',
    city: 'Lille',
    description: 'Installation, configuration et dépannage de vos ordinateurs et logiciels.',
    hourlyRate: 42,
    imageUrl: '',
    available: true,
  },
  {
    firstName: 'Louis',
    lastName: 'Dubois',
    profession: 'Peintre',
    city: 'Lyon',
    description: 'Travaux de peinture intérieure et finitions soignées pour vos pièces de vie.',
    hourlyRate: 38,
    imageUrl: '',
    available: true,
  },
];
